# baseURL = "http://example.com/"

title = "Title of your site"
theme = "phosphor"

[Params]
	description = "Description of your site"
	author = "Author"

	copyrightFrom = 2021
	sitePicture = "images/profile.jpg"

	## Additional CSS file(s). Place .css file(s) in assets/
	# customCss = [ "css/additional1.css", "css/addtional2.css" ]

	## Additional JavaScript file(s)
	# customJs = [ "...", "..." ]

	## Fonts. Put the font files in static/ (in this example, in static/fonts/)
	# bannerFont = "fonts/bannerfont.woff"
	# bannerDescFont = "fonts/bannerdescfont.woff"

	## add mark as draft if the page is a draft.
	## If it is true, the default string is used.
	## You can also specify your own string.
	## default: false
	draftmark = true
	# draftmark = "DRAFT"

[Params.Phosphor]
	colorTheme = 'blue'			# blue (default), red, green, yellow

	## Table of contents (default: true)
	## You can also override this via toc-Parameter in the front matter
	toc = true

	## Page summary in list pages (default: true)
	## You can override this via toc-Parameter of the front matter
	pagelist = true

	## Page navigation (links to previous, up, next) (default: false)
	## You can override this via toc-Parameter of the front matter
	pagenavhead = true
	pagenavfoot = true

	## Font Awesome
	## (checked only with Font Awesome 6.0.0)
	##
	## If you want to use Font Awesome installed on your host (not via CDN),
	## specify the following setting. (default: via CDN)
	## Install css/all.css (or css/all.min.css) and webfonts/ in
	## some directory in static/ .
	## e.g.:
	##   static/fa/css/all.css
	##   static/fa/webfonts/*.{woff2,ttf}
	## The relative path for webfonts/ should be ../webfonts/ from css directory.
	## see also: https://fontawesome.com/docs/web/setup/host-yourself/webfonts
	## If you installed your files in static/, specify "css/all.css" (without "fa/").
	# faLocal = "fa/css/all.css"     # or "fa/all.min.css"

[Params.math]
	enable = true
	use = "katex"				# katex or mathjax (default: katex)
	## If you want to use KaTeX installed on your host (not via CDN),
	## specify the following settings. (default: via CDN)
	## Install KaTeX-files in some directory in static/ .
	## Don't forget to install (copy) contrib/ .
	# katexLocal = "katex/"		# or "/" if you installed your files in static/
	# katexLocalUseMinified = true	# if you want to use minified version


# ------------------------------------------------------------
# syntax-highlighting
#
# see:
#   https://gohugo.io/getting-started/configuration-markup#highlight
#   https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css
#
# [markup]
#   [markup.highlight]
# 	style = "pygments"
